In [1]:
#Advantages of Numpy Arrays:

#Allows several Mathematical Operations
#Faster operations

In [2]:
import numpy as np

### List vs Numpy

In [3]:
from time import process_time

In [4]:
#Time taken by a list

In [6]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(start_time)
print(end_time)
print(end_time - start_time)

2.6875
2.703125
0.015625


In [7]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5  
end_time = process_time()
print(start_time)
print(end_time)
print(end_time - start_time)

2.703125
2.703125
0.0


In [8]:
#Numpy Arrays

In [9]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [11]:
# creating a 1 dim array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [12]:
a.shape

(5,)

In [13]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
b.shape

(2, 5)

In [15]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [16]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [19]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.4757805  0.46485472 0.71991436 0.66452229]
 [0.61402492 0.09803176 0.21617116 0.29005037]
 [0.94555205 0.96696832 0.55559077 0.84778531]]


In [22]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[28 28 59 32 91]
 [82 79 74 63 47]
 [87 26 15 44 84]]


In [23]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [24]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [25]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [26]:
c = np.random.randint(10,90,(5,5))
print(c)

[[56 51 23 84 17]
 [74 55 25 21 65]
 [33 60 73 89 80]
 [21 68 17 70 82]
 [57 56 43 12 26]]


In [27]:
# array dimension
print(c.shape)

(5, 5)


In [28]:
# number of dimensions
print(c.ndim)

2


In [29]:
# number of elements in an array
print(c.size)

25


In [30]:
# checking the data type of the values in the array
print(c.dtype)

int32


### Mathematical operations on a np array

In [31]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [32]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print("***********")
print(b)

[[1 8 8]
 [2 4 7]
 [9 3 7]]
***********
[[15 12 18]
 [17 16 17]
 [18 15 13]]


In [33]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[16 20 26]
 [19 20 24]
 [27 18 20]]
[[-14  -4 -10]
 [-15 -12 -10]
 [ -9 -12  -6]]
[[ 15  96 144]
 [ 34  64 119]
 [162  45  91]]
[[0.06666667 0.66666667 0.44444444]
 [0.11764706 0.25       0.41176471]
 [0.5        0.2        0.53846154]]


In [34]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print("**********")
print(b)

[[3 4 5]
 [9 8 4]
 [5 3 9]]
**********
[[18 14 16]
 [17 10 14]
 [13 14 17]]


In [35]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 18 21]
 [26 18 18]
 [18 17 26]]
[[-15 -10 -11]
 [ -8  -2 -10]
 [ -8 -11  -8]]
[[ 54  56  80]
 [153  80  56]
 [ 65  42 153]]
[[0.16666667 0.28571429 0.3125    ]
 [0.52941176 0.8        0.28571429]
 [0.38461538 0.21428571 0.52941176]]


In [36]:
#Array Manipulation

In [38]:
array = np.random.randint(0,10,(2,3))
print(array)
print("******")
print(array.shape)

[[6 6 6]
 [7 4 9]]
******
(2, 3)


In [40]:
# transpose
trans = np.transpose(array)
print(trans)
print("*****")
print(trans.shape)

[[6 7]
 [6 4]
 [6 9]]
*****
(3, 2)


In [41]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 2 4]
 [8 6 2]]
(2, 3)


In [42]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 8]
 [2 6]
 [4 2]]
(3, 2)


In [43]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 7 1]
 [6 7 1]]
(2, 3)


In [44]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 7]
 [1 6]
 [7 1]]
(3, 2)
